# SPDX-License-Identifier: CECILL-2.1
"""Auto-generated ctypes argtypes/restype declarations for libc4a.

Do not edit by hand. Regenerate with::

    python scripts/generate_ffi_decls.py
"""
from __future__ import annotations

from ctypes import (
    POINTER, c_char, c_char_p, c_double, c_float, c_int, c_int32,
    c_int64, c_size_t, c_uint8, c_uint32, c_uint64, c_void_p,
)

from ._types import MatrixView, FilterStats, SplitResult, TransferMetrics

# Symbols: tuple of (symbol_name, argtypes_tuple, restype).
# restype = None for void; argtypes = () for parameter-less.
SYMBOLS = (
    ("c4a_status_to_string", (c_int,), c_void_p),
    ("c4a_backend_is_available", (c_int,), c_int),
    ("c4a_backend_to_string", (c_int,), c_void_p),
    ("c4a_dtype_size", (c_int,), c_size_t),
    ("c4a_dtype_to_string", (c_int,), c_void_p),
    ("c4a_matrix_view_init_rowmajor", (POINTER(MatrixView), c_void_p, c_int64, c_int64, c_int), c_int),
    ("c4a_matrix_view_init_colmajor", (POINTER(MatrixView), c_void_p, c_int64, c_int64, c_int), c_int),
    ("c4a_matrix_view_init_strided", (POINTER(MatrixView), c_void_p, c_int64, c_int64, c_int64, c_int64, c_int), c_int),
    ("c4a_matrix_view_validate", (POINTER(MatrixView),), c_int),
    ("c4a_context_create", (POINTER(c_void_p),), c_int),
    ("c4a_context_destroy", (c_void_p,), None),
    ("c4a_context_set_seed", (c_void_p, c_uint64), c_int),
    ("c4a_context_get_seed", (c_void_p, POINTER(c_uint64)), c_int),
    ("c4a_context_set_backend", (c_void_p, c_int), c_int),
    ("c4a_context_get_backend", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_context_set_num_threads", (c_void_p, c_int32), c_int),
    ("c4a_context_get_num_threads", (c_void_p, POINTER(c_int32)), c_int),
    ("c4a_context_last_error", (c_void_p,), c_void_p),
    ("c4a_context_clear_error", (c_void_p,), None),
    ("c4a_context_set_user_data", (c_void_p, c_void_p), c_int),
    ("c4a_context_get_user_data", (c_void_p,), c_void_p),
    ("c4a_get_abi_version_major", (), c_uint32),
    ("c4a_get_abi_version_minor", (), c_uint32),
    ("c4a_get_abi_version_patch", (), c_uint32),
    ("c4a_get_abi_version_int", (), c_uint32),
    ("c4a_get_version_string", (), c_void_p),
    ("c4a_get_build_info", (), c_void_p),
    ("c4a_get_git_revision", (), c_void_p),
    ("c4a_check_abi_compatibility", (c_uint32, c_uint32), c_int),
    ("c4a_rng_pcg64_create", (c_uint64, POINTER(c_void_p)), c_int),
    ("c4a_rng_pcg64_destroy", (c_void_p,), None),
    ("c4a_rng_pcg64_set_seed", (c_void_p, c_uint64), c_int),
    ("c4a_rng_pcg64_uint64", (c_void_p, POINTER(c_uint64)), c_int),
    ("c4a_rng_pcg64_uint64_fill", (c_void_p, POINTER(c_uint64), c_size_t), c_int),
    ("c4a_rng_pcg64_standard_normal_fill", (c_void_p, POINTER(c_double), c_size_t), c_int),
    ("c4a_rng_pcg64_advance", (c_void_p, c_uint64), c_int),
    ("c4a_pp_snv_create", (POINTER(c_void_p), c_int, c_int, c_int), c_int),
    ("c4a_pp_snv_destroy", (c_void_p,), None),
    ("c4a_pp_snv_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_lsnv_create", (POINTER(c_void_p), c_int32, c_int32, c_double), c_int),
    ("c4a_pp_lsnv_destroy", (c_void_p,), None),
    ("c4a_pp_lsnv_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_rnv_create", (POINTER(c_void_p), c_int, c_int, c_double), c_int),
    ("c4a_pp_rnv_destroy", (c_void_p,), None),
    ("c4a_pp_rnv_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_area_create", (POINTER(c_void_p), c_int32), c_int),
    ("c4a_pp_area_destroy", (c_void_p,), None),
    ("c4a_pp_area_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_normalize_create", (POINTER(c_void_p), c_double, c_double), c_int),
    ("c4a_pp_normalize_destroy", (c_void_p,), None),
    ("c4a_pp_normalize_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_simple_scale_create", (POINTER(c_void_p),), c_int),
    ("c4a_pp_simple_scale_destroy", (c_void_p,), None),
    ("c4a_pp_simple_scale_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_log_create", (POINTER(c_void_p), c_double, c_double, c_int, c_double), c_int),
    ("c4a_pp_log_destroy", (c_void_p,), None),
    ("c4a_pp_log_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_log_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_log_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_msc_create", (POINTER(c_void_p),), c_int),
    ("c4a_pp_msc_destroy", (c_void_p,), None),
    ("c4a_pp_msc_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_msc_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_msc_inverse_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_msc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_emsc_create", (POINTER(c_void_p), c_int32), c_int),
    ("c4a_pp_emsc_destroy", (c_void_p,), None),
    ("c4a_pp_emsc_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_emsc_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_emsc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_baseline_create", (POINTER(c_void_p),), c_int),
    ("c4a_pp_baseline_destroy", (c_void_p,), None),
    ("c4a_pp_baseline_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_baseline_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_baseline_inverse_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_baseline_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_derivate_create", (POINTER(c_void_p), c_int32, c_double), c_int),
    ("c4a_pp_derivate_destroy", (c_void_p,), None),
    ("c4a_pp_derivate_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_derivate_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_derivate_output_cols", (c_int32, c_int64), c_int64),
    ("c4a_pp_savgol_create", (POINTER(c_void_p), c_int32, c_int32, c_int32, c_double, c_int, c_double), c_int),
    ("c4a_pp_savgol_destroy", (c_void_p,), None),
    ("c4a_pp_savgol_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_first_derivative_create", (POINTER(c_void_p), c_double, c_int32), c_int),
    ("c4a_pp_first_derivative_destroy", (c_void_p,), None),
    ("c4a_pp_first_derivative_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_second_derivative_create", (POINTER(c_void_p), c_double, c_int32), c_int),
    ("c4a_pp_second_derivative_destroy", (c_void_p,), None),
    ("c4a_pp_second_derivative_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_norris_williams_create", (POINTER(c_void_p), c_int32, c_int32, c_int32, c_double), c_int),
    ("c4a_pp_norris_williams_destroy", (c_void_p,), None),
    ("c4a_pp_norris_williams_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_gaussian_create", (POINTER(c_void_p), c_double, c_int32, c_int, c_double, c_double), c_int),
    ("c4a_pp_gaussian_destroy", (c_void_p,), None),
    ("c4a_pp_gaussian_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_detrend_create", (POINTER(c_void_p), c_int32), c_int),
    ("c4a_pp_detrend_destroy", (c_void_p,), None),
    ("c4a_pp_detrend_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_asls_create", (POINTER(c_void_p), c_double, c_double, c_int32, c_double), c_int),
    ("c4a_pp_asls_destroy", (c_void_p,), None),
    ("c4a_pp_asls_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_airpls_create", (POINTER(c_void_p), c_double, c_int32, c_double), c_int),
    ("c4a_pp_airpls_destroy", (c_void_p,), None),
    ("c4a_pp_airpls_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_arpls_create", (POINTER(c_void_p), c_double, c_int32, c_double), c_int),
    ("c4a_pp_arpls_destroy", (c_void_p,), None),
    ("c4a_pp_arpls_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_modpoly_create", (POINTER(c_void_p), c_int32, c_int32, c_double), c_int),
    ("c4a_pp_modpoly_destroy", (c_void_p,), None),
    ("c4a_pp_modpoly_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_imodpoly_create", (POINTER(c_void_p), c_int32, c_int32, c_double), c_int),
    ("c4a_pp_imodpoly_destroy", (c_void_p,), None),
    ("c4a_pp_imodpoly_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_snip_create", (POINTER(c_void_p), c_int32), c_int),
    ("c4a_pp_snip_destroy", (c_void_p,), None),
    ("c4a_pp_snip_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_rolling_ball_create", (POINTER(c_void_p), c_int32, c_int32), c_int),
    ("c4a_pp_rolling_ball_destroy", (c_void_p,), None),
    ("c4a_pp_rolling_ball_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_iasls_create", (POINTER(c_void_p), c_double, c_double, c_int32, c_int32, c_double), c_int),
    ("c4a_pp_iasls_create_ex", (POINTER(c_void_p), c_double, c_double, c_double, c_int32, c_int32, c_int32, c_double), c_int),
    ("c4a_pp_iasls_destroy", (c_void_p,), None),
    ("c4a_pp_iasls_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_beads_create", (POINTER(c_void_p), c_double, c_double, c_double, c_int32, c_double), c_int),
    ("c4a_pp_beads_destroy", (c_void_p,), None),
    ("c4a_pp_beads_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_to_absorbance_create", (POINTER(c_void_p), c_int, c_double, c_int), c_int),
    ("c4a_pp_to_absorbance_destroy", (c_void_p,), None),
    ("c4a_pp_to_absorbance_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_from_absorbance_create", (POINTER(c_void_p), c_int), c_int),
    ("c4a_pp_from_absorbance_destroy", (c_void_p,), None),
    ("c4a_pp_from_absorbance_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_pct_to_frac_create", (POINTER(c_void_p),), c_int),
    ("c4a_pp_pct_to_frac_destroy", (c_void_p,), None),
    ("c4a_pp_pct_to_frac_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_frac_to_pct_create", (POINTER(c_void_p),), c_int),
    ("c4a_pp_frac_to_pct_destroy", (c_void_p,), None),
    ("c4a_pp_frac_to_pct_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_kubelka_munk_create", (POINTER(c_void_p), c_int, c_double), c_int),
    ("c4a_pp_kubelka_munk_destroy", (c_void_p,), None),
    ("c4a_pp_kubelka_munk_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_osc_create", (POINTER(c_void_p), c_int32, c_int), c_int),
    ("c4a_pp_osc_destroy", (c_void_p,), None),
    ("c4a_pp_osc_fit", (c_void_p, MatrixView, POINTER(c_double), c_int64), c_int),
    ("c4a_pp_osc_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_osc_inverse_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_osc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_epo_create", (POINTER(c_void_p), c_int), c_int),
    ("c4a_pp_epo_destroy", (c_void_p,), None),
    ("c4a_pp_epo_fit", (c_void_p, MatrixView, POINTER(c_double), c_int64), c_int),
    ("c4a_pp_epo_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_epo_transform_with_d", (c_void_p, MatrixView, POINTER(c_double), c_int64, MatrixView), c_int),
    ("c4a_pp_epo_inverse_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_epo_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_flex_pca_create", (POINTER(c_void_p), c_double), c_int),
    ("c4a_pp_flex_pca_destroy", (c_void_p,), None),
    ("c4a_pp_flex_pca_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_flex_pca_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_flex_pca_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_flex_pca_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    ("c4a_pp_flex_svd_create", (POINTER(c_void_p), c_double), c_int),
    ("c4a_pp_flex_svd_destroy", (c_void_p,), None),
    ("c4a_pp_flex_svd_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_flex_svd_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_flex_svd_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_flex_svd_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    ("c4a_pp_resampler_create", (POINTER(c_void_p), POINTER(c_double), c_int64, c_int32, c_double, c_double, c_int, c_double, c_int, c_int), c_int),
    ("c4a_pp_resampler_destroy", (c_void_p,), None),
    ("c4a_pp_resampler_fit", (c_void_p, POINTER(c_double), c_int64), c_int),
    ("c4a_pp_resampler_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_resampler_output_cols", (c_void_p,), c_int64),
    ("c4a_pp_resampler_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_crop_create", (POINTER(c_void_p), c_int64, c_int64), c_int),
    ("c4a_pp_crop_destroy", (c_void_p,), None),
    ("c4a_pp_crop_output_cols", (c_void_p, c_int64), c_int64),
    ("c4a_pp_crop_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_resample_create", (POINTER(c_void_p), c_int64), c_int),
    ("c4a_pp_resample_destroy", (c_void_p,), None),
    ("c4a_pp_resample_output_cols", (c_void_p, c_int64), c_int64),
    ("c4a_pp_resample_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_kbins_disc_create", (POINTER(c_void_p), c_int32, c_int32), c_int),
    ("c4a_pp_kbins_disc_destroy", (c_void_p,), None),
    ("c4a_pp_kbins_disc_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_kbins_disc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_kbins_disc_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_range_disc_create", (POINTER(c_void_p), POINTER(c_double), c_int64), c_int),
    ("c4a_pp_range_disc_destroy", (c_void_p,), None),
    ("c4a_pp_range_disc_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_split_result_destroy", (POINTER(SplitResult),), None),
    ("c4a_split_kennard_stone_create", (POINTER(c_void_p), c_double), c_int),
    ("c4a_split_kennard_stone_destroy", (c_void_p,), None),
    ("c4a_split_kennard_stone_split", (c_void_p, MatrixView, POINTER(SplitResult)), c_int),
    ("c4a_split_spxy_create", (POINTER(c_void_p), c_double), c_int),
    ("c4a_split_spxy_destroy", (c_void_p,), None),
    ("c4a_split_spxy_split", (c_void_p, MatrixView, MatrixView, POINTER(SplitResult)), c_int),
    ("c4a_split_spxy_fold_create", (POINTER(c_void_p), c_int32, c_int32), c_int),
    ("c4a_split_spxy_fold_destroy", (c_void_p,), None),
    ("c4a_split_spxy_fold_n_splits", (c_void_p, POINTER(c_int32)), c_int),
    ("c4a_split_spxy_fold_split_fold", (c_void_p, MatrixView, MatrixView, c_int32, POINTER(SplitResult)), c_int),
    ("c4a_split_spxy_g_fold_create", (POINTER(c_void_p), c_int32, c_int32, c_int32), c_int),
    ("c4a_split_spxy_g_fold_destroy", (c_void_p,), None),
    ("c4a_split_spxy_g_fold_n_splits", (c_void_p, POINTER(c_int32)), c_int),
    ("c4a_split_spxy_g_fold_split_fold", (c_void_p, MatrixView, MatrixView, POINTER(c_int64), c_int64, c_int32, POINTER(SplitResult)), c_int),
    ("c4a_split_kmeans_create", (POINTER(c_void_p), c_double, c_uint64, c_int32), c_int),
    ("c4a_split_kmeans_destroy", (c_void_p,), None),
    ("c4a_split_kmeans_split", (c_void_p, MatrixView, POINTER(SplitResult)), c_int),
    ("c4a_split_kbins_stratified_create", (POINTER(c_void_p), c_double, c_uint64, c_int32, c_int32), c_int),
    ("c4a_split_kbins_stratified_destroy", (c_void_p,), None),
    ("c4a_split_kbins_stratified_split", (c_void_p, MatrixView, POINTER(SplitResult)), c_int),
    ("c4a_split_binned_strat_group_kfold_create", (POINTER(c_void_p), c_int32, c_int32, c_int32, c_int32, c_uint64), c_int),
    ("c4a_split_binned_strat_group_kfold_destroy", (c_void_p,), None),
    ("c4a_split_binned_strat_group_kfold_n_splits", (c_void_p, POINTER(c_int32)), c_int),
    ("c4a_split_binned_strat_group_kfold_split_fold", (c_void_p, MatrixView, POINTER(c_int64), c_int64, c_int32, POINTER(SplitResult)), c_int),
    ("c4a_split_systematic_circular_create", (POINTER(c_void_p), c_double, c_uint64), c_int),
    ("c4a_split_systematic_circular_destroy", (c_void_p,), None),
    ("c4a_split_systematic_circular_split", (c_void_p, MatrixView, POINTER(SplitResult)), c_int),
    ("c4a_split_split_splitter_create", (POINTER(c_void_p), c_double, c_uint64), c_int),
    ("c4a_split_split_splitter_destroy", (c_void_p,), None),
    ("c4a_split_split_splitter_split", (c_void_p, MatrixView, POINTER(SplitResult)), c_int),
    ("c4a_filter_y_outlier_create", (POINTER(c_void_p), c_int, c_double, c_double, c_double), c_int),
    ("c4a_filter_y_outlier_destroy", (c_void_p,), None),
    ("c4a_filter_y_outlier_fit", (c_void_p, POINTER(c_double), c_int64), c_int),
    ("c4a_filter_y_outlier_apply", (c_void_p, POINTER(c_double), c_int64, POINTER(c_uint8), POINTER(FilterStats)), c_int),
    ("c4a_filter_y_outlier_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_filter_leverage_create", (POINTER(c_void_p), c_int32, c_double, c_int, c_double, c_int32, c_int), c_int),
    ("c4a_filter_leverage_destroy", (c_void_p,), None),
    ("c4a_filter_leverage_fit", (c_void_p, MatrixView), c_int),
    ("c4a_filter_leverage_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_filter_leverage_apply", (c_void_p, MatrixView, POINTER(c_uint8), POINTER(FilterStats)), c_int),
    ("c4a_filter_leverage_threshold", (c_void_p,), c_double),
    ("c4a_filter_quality_create", (POINTER(c_void_p), c_double, c_double, c_double, c_int, c_double, c_int, c_double, c_int), c_int),
    ("c4a_filter_quality_destroy", (c_void_p,), None),
    ("c4a_filter_quality_apply", (c_void_p, MatrixView, POINTER(c_uint8), POINTER(FilterStats)), c_int),
    ("c4a_filter_composite_create", (POINTER(c_void_p), c_int), c_int),
    ("c4a_filter_composite_destroy", (c_void_p,), None),
    ("c4a_filter_composite_add_leverage", (c_void_p, c_void_p), c_int),
    ("c4a_filter_composite_add_quality", (c_void_p, c_void_p), c_int),
    ("c4a_filter_composite_apply", (c_void_p, MatrixView, POINTER(c_uint8), POINTER(FilterStats)), c_int),
    ("c4a_signal_detect", (MatrixView, POINTER(c_double), c_int64, c_double, POINTER(c_int), POINTER(c_double), c_void_p), c_int),
    ("c4a_metric_rmse", (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_metric_mae", (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_metric_bias", (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_metric_sep", (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_metric_rpd", (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_metric_rpiq", (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_metric_r2", (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_metric_nrmse", (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_util_hotelling_t2", (MatrixView, c_int32, c_double, POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_util_q_residuals", (MatrixView, c_int32, c_double, POINTER(c_double), c_int64, POINTER(c_double)), c_int),
    ("c4a_transfer_metrics_compute", (MatrixView, MatrixView, c_int32, c_int32, c_uint64, POINTER(TransferMetrics)), c_int),
    ("c4a_pp_fck_static_create", (POINTER(c_void_p), c_int32, POINTER(c_double), c_int32, POINTER(c_double), c_int32), c_int),
    ("c4a_pp_fck_static_destroy", (c_void_p,), None),
    ("c4a_pp_fck_static_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_fck_static_output_cols", (c_int32, c_int32, POINTER(c_int32)), c_int),
    ("c4a_pp_wavelet_create", (POINTER(c_void_p), c_int, c_int), c_int),
    ("c4a_pp_wavelet_destroy", (c_void_p,), None),
    ("c4a_pp_wavelet_output_cols", (c_void_p, c_int64, POINTER(c_int64)), c_int),
    ("c4a_pp_wavelet_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_haar_create", (POINTER(c_void_p),), c_int),
    ("c4a_pp_haar_destroy", (c_void_p,), None),
    ("c4a_pp_haar_output_cols", (c_int64, POINTER(c_int64)), c_int),
    ("c4a_pp_haar_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_wavelet_denoise_create", (POINTER(c_void_p), c_int, c_int, c_int32, c_int, c_int), c_int),
    ("c4a_pp_wavelet_denoise_destroy", (c_void_p,), None),
    ("c4a_pp_wavelet_denoise_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_wavelet_features_create", (POINTER(c_void_p), c_int, c_int, c_int32), c_int),
    ("c4a_pp_wavelet_features_create_ex", (POINTER(c_void_p), c_int, c_int, c_int32, c_int), c_int),
    ("c4a_pp_wavelet_features_destroy", (c_void_p,), None),
    ("c4a_pp_wavelet_features_output_cols", (c_void_p, c_int64, POINTER(c_int64)), c_int),
    ("c4a_pp_wavelet_features_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_wavelet_pca_create", (POINTER(c_void_p), c_int, c_int, c_int32, c_double), c_int),
    ("c4a_pp_wavelet_pca_destroy", (c_void_p,), None),
    ("c4a_pp_wavelet_pca_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_wavelet_pca_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_wavelet_pca_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_wavelet_pca_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    ("c4a_pp_wavelet_svd_create", (POINTER(c_void_p), c_int, c_int, c_int32, c_double), c_int),
    ("c4a_pp_wavelet_svd_destroy", (c_void_p,), None),
    ("c4a_pp_wavelet_svd_fit", (c_void_p, MatrixView), c_int),
    ("c4a_pp_wavelet_svd_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_pp_wavelet_svd_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_pp_wavelet_svd_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    ("c4a_filter_x_outlier_create", (POINTER(c_void_p), c_int32, c_int, c_double, c_int32, c_double, c_uint64, c_int32, c_int64), c_int),
    ("c4a_filter_x_outlier_destroy", (c_void_p,), None),
    ("c4a_filter_x_outlier_fit", (c_void_p, MatrixView), c_int),
    ("c4a_filter_x_outlier_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("c4a_filter_x_outlier_apply", (c_void_p, MatrixView, POINTER(c_uint8), POINTER(FilterStats)), c_int),
    ("c4a_aug_gaussian_noise_create", (POINTER(c_void_p), c_void_p, c_double), c_int),
    ("c4a_aug_gaussian_noise_destroy", (c_void_p,), None),
    ("c4a_aug_gaussian_noise_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_multiplicative_noise_create", (POINTER(c_void_p), c_void_p, c_double), c_int),
    ("c4a_aug_multiplicative_noise_destroy", (c_void_p,), None),
    ("c4a_aug_multiplicative_noise_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_spike_noise_create", (POINTER(c_void_p), c_void_p, c_int32, c_int32, c_double, c_double), c_int),
    ("c4a_aug_spike_noise_destroy", (c_void_p,), None),
    ("c4a_aug_spike_noise_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_hetero_noise_create", (POINTER(c_void_p), c_void_p, c_double, c_double), c_int),
    ("c4a_aug_hetero_noise_destroy", (c_void_p,), None),
    ("c4a_aug_hetero_noise_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_linear_drift_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_double), c_int),
    ("c4a_aug_linear_drift_destroy", (c_void_p,), None),
    ("c4a_aug_linear_drift_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_poly_drift_create", (POINTER(c_void_p), c_void_p, c_int32, POINTER(c_double), POINTER(c_double)), c_int),
    ("c4a_aug_poly_drift_destroy", (c_void_p,), None),
    ("c4a_aug_poly_drift_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_path_length_create", (POINTER(c_void_p), c_void_p, c_double, c_double), c_int),
    ("c4a_aug_path_length_destroy", (c_void_p,), None),
    ("c4a_aug_path_length_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_wavelength_shift_create", (POINTER(c_void_p), c_void_p, c_double, c_double, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_wavelength_shift_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_wavelength_shift_destroy", (c_void_p,), None),
    ("c4a_aug_wavelength_stretch_create", (POINTER(c_void_p), c_void_p, c_double, c_double, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_wavelength_stretch_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_wavelength_stretch_destroy", (c_void_p,), None),
    ("c4a_aug_local_warp_create", (POINTER(c_void_p), c_void_p, c_int32, c_double, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_local_warp_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_local_warp_destroy", (c_void_p,), None),
    ("c4a_aug_band_perturb_create", (POINTER(c_void_p), c_void_p, c_int32, c_int32, c_int32, c_double, c_double, c_double, c_double), c_int),
    ("c4a_aug_band_perturb_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_band_perturb_destroy", (c_void_p,), None),
    ("c4a_aug_band_mask_create", (POINTER(c_void_p), c_void_p, c_int32, c_int32, c_int32, c_int32, c_int32), c_int),
    ("c4a_aug_band_mask_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_band_mask_destroy", (c_void_p,), None),
    ("c4a_aug_channel_dropout_create", (POINTER(c_void_p), c_void_p, c_double, c_int32), c_int),
    ("c4a_aug_channel_dropout_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_channel_dropout_destroy", (c_void_p,), None),
    ("c4a_aug_gauss_jitter_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_int32), c_int),
    ("c4a_aug_gauss_jitter_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_gauss_jitter_destroy", (c_void_p,), None),
    ("c4a_aug_unsharp_mask_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_int32), c_int),
    ("c4a_aug_unsharp_mask_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_unsharp_mask_destroy", (c_void_p,), None),
    ("c4a_aug_magnitude_warp_create", (POINTER(c_void_p), c_void_p, c_int32, c_double, c_double, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_magnitude_warp_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_magnitude_warp_destroy", (c_void_p,), None),
    ("c4a_aug_local_clip_create", (POINTER(c_void_p), c_void_p, c_int32, c_int32, c_int32), c_int),
    ("c4a_aug_local_clip_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_local_clip_destroy", (c_void_p,), None),
    ("c4a_aug_mixup_create", (POINTER(c_void_p), c_void_p, c_double), c_int),
    ("c4a_aug_mixup_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_mixup_destroy", (c_void_p,), None),
    ("c4a_aug_local_mixup_create", (POINTER(c_void_p), c_void_p, c_double, c_int32), c_int),
    ("c4a_aug_local_mixup_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_local_mixup_destroy", (c_void_p,), None),
    ("c4a_aug_scatter_sim_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_double), c_int),
    ("c4a_aug_scatter_sim_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_scatter_sim_destroy", (c_void_p,), None),
    ("c4a_aug_particle_size_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_int, c_double, c_double, c_double, c_double, c_double, c_int, c_double, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_particle_size_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_particle_size_destroy", (c_void_p,), None),
    ("c4a_aug_emsc_distort_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_double, c_int32, c_double, c_double, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_emsc_distort_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_emsc_distort_destroy", (c_void_p,), None),
    ("c4a_aug_batch_effect_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_int32, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_batch_effect_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_batch_effect_destroy", (c_void_p,), None),
    ("c4a_aug_instrument_broaden_create", (POINTER(c_void_p), c_void_p, c_double, c_int, c_double, c_double, c_int32, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_instrument_broaden_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_instrument_broaden_destroy", (c_void_p,), None),
    ("c4a_aug_dead_band_create", (POINTER(c_void_p), c_void_p, c_int32, c_int32, c_int32, c_double, c_double, c_int32), c_int),
    ("c4a_aug_dead_band_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_dead_band_destroy", (c_void_p,), None),
    ("c4a_aug_temperature_create", (POINTER(c_void_p), c_void_p, c_double, c_int, c_double, c_double, c_int, c_int, c_int, c_int, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_temperature_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_temperature_destroy", (c_void_p,), None),
    ("c4a_aug_moisture_create", (POINTER(c_void_p), c_void_p, c_double, c_int, c_double, c_double, c_double, c_double, c_double, c_double, c_int, c_int, POINTER(c_double), c_int64), c_int),
    ("c4a_aug_moisture_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_moisture_destroy", (c_void_p,), None),
    ("c4a_aug_detector_rolloff_create", (POINTER(c_void_p), c_void_p, c_int32, c_double, c_double, c_int32), c_int),
    ("c4a_aug_detector_rolloff_apply", (c_void_p, MatrixView, MatrixView, MatrixView), c_int),
    ("c4a_aug_detector_rolloff_destroy", (c_void_p,), None),
    ("c4a_aug_stray_light_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_int32), c_int),
    ("c4a_aug_stray_light_apply", (c_void_p, MatrixView, MatrixView, MatrixView), c_int),
    ("c4a_aug_stray_light_destroy", (c_void_p,), None),
    ("c4a_aug_edge_curve_create", (POINTER(c_void_p), c_void_p, c_double, c_int32, c_double, c_double), c_int),
    ("c4a_aug_edge_curve_apply", (c_void_p, MatrixView, MatrixView, MatrixView), c_int),
    ("c4a_aug_edge_curve_destroy", (c_void_p,), None),
    ("c4a_aug_truncated_peak_create", (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_double, c_double, c_int32, c_int32), c_int),
    ("c4a_aug_truncated_peak_apply", (c_void_p, MatrixView, MatrixView, MatrixView), c_int),
    ("c4a_aug_truncated_peak_destroy", (c_void_p,), None),
    ("c4a_aug_edge_artifacts_create", (POINTER(c_void_p), c_void_p, c_int32, c_double, c_int32), c_int),
    ("c4a_aug_edge_artifacts_apply", (c_void_p, MatrixView, MatrixView, MatrixView), c_int),
    ("c4a_aug_edge_artifacts_destroy", (c_void_p,), None),
    ("c4a_aug_spline_smooth_create", (POINTER(c_void_p), c_void_p), c_int),
    ("c4a_aug_spline_smooth_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_spline_smooth_destroy", (c_void_p,), None),
    ("c4a_aug_spline_x_perturb_create", (POINTER(c_void_p), c_void_p, c_int32, c_double, c_double, c_double), c_int),
    ("c4a_aug_spline_x_perturb_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_spline_x_perturb_destroy", (c_void_p,), None),
    ("c4a_aug_spline_y_perturb_create", (POINTER(c_void_p), c_void_p, c_int32, c_double), c_int),
    ("c4a_aug_spline_y_perturb_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_spline_y_perturb_destroy", (c_void_p,), None),
    ("c4a_aug_spline_x_simplify_create", (POINTER(c_void_p), c_void_p, c_int32, c_int32), c_int),
    ("c4a_aug_spline_x_simplify_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_spline_x_simplify_destroy", (c_void_p,), None),
    ("c4a_aug_spline_curve_simplify_create", (POINTER(c_void_p), c_void_p, c_int32, c_int32), c_int),
    ("c4a_aug_spline_curve_simplify_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_spline_curve_simplify_destroy", (c_void_p,), None),
    ("c4a_aug_rotate_translate_create", (POINTER(c_void_p), c_void_p, c_double, c_double), c_int),
    ("c4a_aug_rotate_translate_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_rotate_translate_destroy", (c_void_p,), None),
    ("c4a_aug_random_x_op_create", (POINTER(c_void_p), c_void_p, c_int32, c_double, c_double), c_int),
    ("c4a_aug_random_x_op_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("c4a_aug_random_x_op_destroy", (c_void_p,), None),
)


def apply_argtypes(lib):
    """Bind argtypes/restype for every exported function on ``lib``."""
    for name, argtypes, restype in SYMBOLS:
        fn = getattr(lib, name, None)
        if fn is None:
            continue
        fn.argtypes = list(argtypes)
        fn.restype = restype
