function res = ga_select(X, Y, n_components, n_generations, population_size, ...
                          min_features, max_features, mutation_rate, seed)
if nargin < 4 || isempty(n_generations),   n_generations = 50;   end
if nargin < 5 || isempty(population_size), population_size = 50; end
if nargin < 6 || isempty(min_features),    min_features = 1;     end
if nargin < 7 || isempty(max_features),    max_features = size(X, 2); end
if nargin < 8 || isempty(mutation_rate),   mutation_rate = 0.01; end
if nargin < 9 || isempty(seed),            seed = 0;             end
params = struct("n_generations",   int32(n_generations), ...
                "population_size", int32(population_size), ...
                "min_features",    int32(min_features), ...
                "max_features",    int32(max_features), ...
                "mutation_rate",   double(mutation_rate), ...
                "seed",            uint64(seed));
res = pls4all.n4m_method_fit_mex("ga_select", double(X), double(Y), ...
                                  int32(n_components), params);
end
