function res = irf_select(X, Y, n_components, n_iterations, window_size, ...
                            initial_intervals, top_k, seed)
if nargin < 4 || isempty(n_iterations),      n_iterations = 100;      end
if nargin < 5 || isempty(window_size),       window_size = 10;        end
if nargin < 6 || isempty(initial_intervals), initial_intervals = 10;  end
if nargin < 7 || isempty(top_k),             top_k = 5;               end
if nargin < 8 || isempty(seed),              seed = 0;                end
params = struct("n_iterations",      int32(n_iterations), ...
                "window_size",       int32(window_size), ...
                "initial_intervals", int32(initial_intervals), ...
                "top_k",             int32(top_k), ...
                "seed",              uint64(seed));
res = pls4all.n4m_method_fit_mex("irf_select", double(X), double(Y), ...
                                  int32(n_components), params);
end
