function res = random_frog_select(X, Y, n_components, n_iterations, ...
                                    initial_size, min_size, max_size, top_k, seed)
if nargin < 4 || isempty(n_iterations), n_iterations = 100; end
if nargin < 5 || isempty(initial_size), initial_size = 30;  end
if nargin < 6 || isempty(min_size),     min_size = 1;        end
if nargin < 7 || isempty(max_size),     max_size = size(X, 2); end
if nargin < 8 || isempty(top_k),        top_k = 10;          end
if nargin < 9 || isempty(seed),         seed = 0;            end
params = struct("n_iterations", int32(n_iterations), ...
                "initial_size", int32(initial_size), ...
                "min_size",     int32(min_size), ...
                "max_size",     int32(max_size), ...
                "top_k",        int32(top_k), ...
                "seed",         uint64(seed));
res = pls4all.p4a_method_fit_mex("random_frog_select", double(X), double(Y), ...
                                  int32(n_components), params);
end
