function res = vissa_select(X, Y, n_components, n_iterations, n_submodels, ...
                              ratio_kept, threshold, floor_probability, seed)
if nargin < 4 || isempty(n_iterations),       n_iterations = 20;      end
if nargin < 5 || isempty(n_submodels),        n_submodels = 100;      end
if nargin < 6 || isempty(ratio_kept),         ratio_kept = 0.1;       end
if nargin < 7 || isempty(threshold),          threshold = 0.5;        end
if nargin < 8 || isempty(floor_probability),  floor_probability = 0.01; end
if nargin < 9 || isempty(seed),               seed = 0;               end
params = struct("n_iterations", int32(n_iterations), ...
                "n_submodels",  int32(n_submodels), ...
                "ratio_kept",   double(ratio_kept), ...
                "threshold",    double(threshold), ...
                "floor_probability", double(floor_probability), ...
                "seed",         uint64(seed));
res = pls4all.n4m_method_fit_mex("vissa_select", double(X), double(Y), ...
                                  int32(n_components), params);
end
