# SPDX-License-Identifier: CECILL-2.1
#
# Parity gate for the n4m R binding.
#
# Loads the installed `n4m` package, fits SIMPLS PLS regression
# on the same deterministic (X, Y) used by the WASM smoke, and
# compares results to bindings/js/test/parity_fixture.json (which was
# generated by the native Python binding).

suppressPackageStartupMessages({
  library(n4m)
  library(jsonlite)
})

cat("R n4m version:", n4m_version(), "\n")
cat("R n4m ABI:", paste(n4m_abi_version(), collapse = "."), "\n")

# Deterministic input — same as bindings/js/test/generate_parity_fixture.py.
n <- 50L
p <- 5L
q <- 1L
X <- matrix(0, nrow = n, ncol = p)
Y <- matrix(0, nrow = n, ncol = q)
for (i in seq_len(n)) {
  for (j in seq_len(p)) {
    X[i, j] <- sin((i) * (j) * 0.3)
  }
  Y[i, 1] <- X[i, 1] + 0.5 * X[i, 2] - 0.3 * X[i, 3]
}

# R uses 1-based indices, so i*j*0.3 matches Python's (i+1)*(j+1)*0.3.

fit <- n4m_fit(X, Y, algo = "pls_simpls", n_components = 3L)
preds <- n4m_predict(fit, X)

# Load the fixture committed by the WASM binding.
args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("--file=", args, value = TRUE)
script_path <- if (length(file_arg) > 0) {
  sub("--file=", "", file_arg[1])
} else {
  ""
}
script_dir <- if (nzchar(script_path)) {
  dirname(normalizePath(script_path))
} else {
  getwd()
}
fixture_path <- normalizePath(file.path(script_dir, "..", "js", "test",
                                          "parity_fixture.json"),
                                mustWork = TRUE)
ref <- fromJSON(fixture_path)

ref_preds <- matrix(unlist(ref$predictions), nrow = n, ncol = q,
                     byrow = FALSE)

# Compare predictions (predict in the R binding doesn't expose
# x_mean / coefficients directly).
diff <- preds - ref_preds
rmse_abs <- sqrt(mean(diff * diff))
rmse_rel <- rmse_abs / max(1e-12, sqrt(mean(ref_preds * ref_preds)))

cat(sprintf("R predictions vs native fixture: rmse_rel = %.3e\n",
            rmse_rel))
cat("First 3 R preds:    ", sprintf("%.6f ", preds[1:3, 1]), "\n")
cat("First 3 fixture:    ", sprintf("%.6f ", ref_preds[1:3, 1]), "\n")

if (rmse_rel > 1e-6) {
  stop(sprintf("R parity failure: rmse_rel = %.3e > 1e-6", rmse_rel))
}
cat("R smoke + parity OK\n")
