#!/usr/bin/env python3
"""Generate a self-contained Python package directory for a distribution.

The bindings/python source tree carries BOTH modules — `n4m` (the full surface)
and `pls4all` (the slim PLS-only subset). PyPI ships them as two packages. This
emits a self-contained `bindings/python_<pkg>/` that ships exactly ONE module,
with a baked package name (a static `[project].name` cannot be overridden at
build time). `release-wheels.yml` builds each via cibuildwheel; libn4m is staged
into `<module>/lib/` by `build_libn4m_in_wheel.sh`.

    make_python_package.py --all
    make_python_package.py --name nirs4all-methods   # -> bindings/python_nirs4all_methods/
    make_python_package.py --name pls4all            # -> bindings/python_pls4all/
"""
from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC_PKG = REPO / "bindings" / "python"

PACKAGES = {
    "nirs4all-methods": {
        "module": "n4m", "dir": "python_nirs4all_methods",
        "description": "nirs4all-methods — portable PLS / NIRS engine (full surface) over the libn4m C ABI.",
    },
    "pls4all": {
        "module": "pls4all", "dir": "python_pls4all",
        "description": "pls4all — slim PLS-only subset of nirs4all-methods over the libn4m C ABI.",
    },
}

_PYPROJECT = '''# GENERATED by bindings/python/scripts/make_python_package.py — do not edit.
[build-system]
requires = ["setuptools>=77", "wheel", "packaging>=24.2"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "{version}"
description = "{description}"
authors = [{{ name = "Grégory Beurier and contributors" }}]
license = "CECILL-2.1"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy>=1.21"]

[project.urls]
Homepage = "https://github.com/GBeurier/pls4all"
Repository = "https://github.com/GBeurier/pls4all"

[tool.setuptools.packages.find]
where = ["src"]
include = ["{module}", "{module}.*"]

# libn4m is staged into {module}/lib/ by scripts/build_libn4m_in_wheel.sh.
[tool.setuptools.package-data]
{module} = ["lib/libn4m*", "lib/*.so", "lib/*.so.*", "lib/*.dylib", "lib/*.dll"]
'''

_README = '''# {name}

{description}

The wheel bundles the `libn4m` shared library, so `pip install {name}` is
self-contained — no separate native build is required.

```python
import {module}

print({module}.version())      # project version + ABI, e.g. "{version}+abi.1.9.0"
print({module}.abi_version())  # ABI triple, e.g. (1, 9, 0)
```

`{module}` loads `libn4m` via `ctypes.CDLL` and exposes a Pythonic `Context` /
`Config`, the method fit/predict surface, and a scikit-learn-compatible estimator
layer (`{module}.sklearn`). `scikit-learn` is an optional dependency; the core
`import {module}` works with NumPy alone.

See <https://github.com/GBeurier/nirs4all-methods> for documentation.
'''


def _version() -> str:
    m = re.search(r'^version\s*=\s*"([^"]+)"', (SRC_PKG / "pyproject.toml").read_text(), re.M)
    return m.group(1) if m else "0.0.0"


def generate(name: str) -> Path:
    spec = PACKAGES[name]
    module = spec["module"]
    out = REPO / "bindings" / spec["dir"]
    if out.exists():
        shutil.rmtree(out)
    (out / "src").mkdir(parents=True)
    ignore = shutil.ignore_patterns("__pycache__", "*.pyc", "lib")  # lib/ staged at build
    shutil.copytree(SRC_PKG / "src" / module, out / "src" / module, ignore=ignore)
    for asset in ("setup.py", "LICENSE"):
        shutil.copy2(SRC_PKG / asset, out / asset)
    # Generate a per-package README — do NOT copy bindings/python/README.md,
    # which documents the slim `pls4all` surface and would mislabel the full
    # `nirs4all-methods` (module `n4m`) package on PyPI.
    (out / "README.md").write_text(_README.format(
        name=name, module=module, description=spec["description"], version=_version()))
    (out / "pyproject.toml").write_text(_PYPROJECT.format(
        name=name, version=_version(), module=module, description=spec["description"]))
    # Per-module smoke test (cibuildwheel CIBW_TEST_COMMAND target).
    (out / "tests").mkdir()
    # abi_version() forces the embedded libn4m to load and respond, and is
    # exposed by both modules (the slim pls4all subset has no `python`
    # submodule, so importing it directly would fail there).
    (out / "tests" / "test_import.py").write_text(
        f'def test_import_and_load():\n'
        f'    import {module}\n'
        f'    assert {module}.__version__\n'
        f'    assert {module}.abi_version()  # loads + queries the embedded libn4m\n')
    print(f"generated {out.relative_to(REPO)}  (name={name}, module={module})")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--name", choices=sorted(PACKAGES))
    g.add_argument("--all", action="store_true")
    args = ap.parse_args(argv)
    for name in (sorted(PACKAGES) if args.all else [args.name]):
        generate(name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
