# SPDX-License-Identifier: CECILL-2.1
#
# Parity gate for the Julia binding. Reuses
# bindings/js/test/parity_fixture.json generated by the native Python
# binding.

using Pls4all
using JSON
using Test

println("Julia pls4all version: ", Pls4all.version())
println("Julia pls4all ABI: ",
        join(Pls4all.abi_version(), "."))

# Deterministic input matching bindings/js/test/generate_parity_fixture.py.
n, p, q = 50, 5, 1
X = zeros(Float64, n, p)
Y = zeros(Float64, n, q)
for i in 1:n
    for j in 1:p
        X[i, j] = sin(i * j * 0.3)
    end
    Y[i, 1] = X[i, 1] + 0.5 * X[i, 2] - 0.3 * X[i, 3]
end

m = Pls4all.pls_fit(X, Y; n_components = 3)
println("Julia coefficients: ",
        [round(v, digits=6) for v in m.coefficients])
println("Julia x_mean:       ",
        [round(v, digits=6) for v in m.x_mean])
println("Julia y_mean:       ",
        [round(v, digits=6) for v in m.y_mean])

# Compare with fixture.
script_dir = @__DIR__
fixture_path = joinpath(script_dir, "..", "..", "..", "js", "test",
                         "parity_fixture.json")
ref = JSON.parsefile(abspath(fixture_path))

function rmse_rel(actual, expected)
    a = collect(Float64, actual)
    e = collect(Float64, expected)
    diff = a .- e
    abs_rmse = sqrt(sum(diff .^ 2) / length(a))
    return abs_rmse / max(1e-12,
                           sqrt(sum(e .^ 2) / length(e)))
end

coefs_rel = rmse_rel(vec(m.coefficients), ref["coefficients"])
xm_rel = rmse_rel(m.x_mean, ref["x_mean"])
ym_rel = rmse_rel(m.y_mean, ref["y_mean"])
preds_rel = rmse_rel(vec(m.predictions), ref["predictions"])

println("\nParity vs native Python pls4all:")
println("  coefficients rmse_rel: ", coefs_rel)
println("  x_mean       rmse_rel: ", xm_rel)
println("  y_mean       rmse_rel: ", ym_rel)
println("  predictions  rmse_rel: ", preds_rel)

tol = 1e-6
@testset "Pls4all Julia parity" begin
    @test coefs_rel <= tol
    @test xm_rel <= tol
    @test ym_rel <= tol
    @test preds_rel <= tol
end
println("\nJulia smoke + parity OK")
