/* SPDX-License-Identifier: CECILL-2.1 */
/* chemometrics4all visibility macros — generated by CMake from c4a_export.h.in.
 *
 * C4A_API:   default-visibility / dllexport when building libc4a,
 *            dllimport when consuming libc4a from another shared library,
 *            empty on static / archive builds.
 * C4A_LOCAL: hidden visibility for internal symbols that may end up in
 *            extern "C" sections.
 *
 * The C/C++ public header `chemometrics4all/c4a.h` includes this file before declaring
 * any function. Users of chemometrics4all never include this header directly. */
#ifndef CHEMOMETRICS4ALL_C4A_EXPORT_H
#define CHEMOMETRICS4ALL_C4A_EXPORT_H

#if defined(_WIN32) || defined(__CYGWIN__)
#  ifdef CHEMOMETRICS4ALL_BUILDING_DLL
#    ifdef __GNUC__
#      define C4A_API __attribute__((dllexport))
#    else
#      define C4A_API __declspec(dllexport)
#    endif
#  elif defined(CHEMOMETRICS4ALL_STATIC)
#    define C4A_API
#  else
#    ifdef __GNUC__
#      define C4A_API __attribute__((dllimport))
#    else
#      define C4A_API __declspec(dllimport)
#    endif
#  endif
#  define C4A_LOCAL
#else
#  if __GNUC__ >= 4
#    define C4A_API   __attribute__((visibility("default")))
#    define C4A_LOCAL __attribute__((visibility("hidden")))
#  else
#    define C4A_API
#    define C4A_LOCAL
#  endif
#endif

#endif /* CHEMOMETRICS4ALL_C4A_EXPORT_H */
