function test_parity()
% test_parity  Octave / MATLAB binding parity gate against the native
% Python pls4all reference. The fixture is regenerated by the Python
% binding in bindings/js/test/generate_parity_fixture.py and shared
% across all bindings (WASM, R, Julia, MEX) so they all agree on the
% same byte-equivalent reference.
%
% This test builds the same deterministic (X, Y) the Python generator
% writes, calls pls4all.pls_fit through the MEX shim, and asserts that
% coefficients / x_mean / y_mean / predictions match the fixture to
% < 1e-12 (relative L2). Exits with status 1 on failure so CI can
% gate.

repo_root = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
fixture_path = fullfile(repo_root, "bindings", "js", "test", ...
                         "parity_fixture.json");
addpath(fullfile(repo_root, "bindings", "matlab"));

if exist(fixture_path, "file") ~= 2
    error("test_parity:fixture", "Missing fixture: %s", fixture_path);
end

fixture = read_fixture(fixture_path);

n = fixture.n;
p = fixture.p;
q = fixture.q;
n_components = fixture.n_components;

% Build the same deterministic input the Python generator wrote.
X = zeros(n, p);
Y = zeros(n, q);
for i = 1:n
    for j = 1:p
        X(i, j) = sin(i * j * 0.3);
    end
    Y(i, 1) = X(i, 1) + 0.5 * X(i, 2) - 0.3 * X(i, 3);
end

% Fit through the MEX shim.
[coefs, x_mean, y_mean, preds] = pls4all.pls_fit(X, Y, n_components);

fixture_coefs = reshape(fixture.coefficients, p, q);
fixture_x_mean = reshape(fixture.x_mean, 1, p);
fixture_y_mean = reshape(fixture.y_mean, 1, q);
fixture_preds = reshape(fixture.predictions, n, q);

% Robust relative L2 norm. Reference vectors are nonzero by construction.
rms_rel = @(a, b) norm(a(:) - b(:)) / max(norm(b(:)), eps);

err_coefs = rms_rel(coefs, fixture_coefs);
err_x_mean = rms_rel(x_mean, fixture_x_mean);
err_y_mean = rms_rel(y_mean, fixture_y_mean);
err_preds = rms_rel(preds, fixture_preds);

fprintf("pls4all.version()        = %s\n", pls4all.version());
fprintf("fixture pls4all_version  = %s\n", fixture.pls4all_version);
fprintf("rmse_rel coefficients    = %.3e\n", err_coefs);
fprintf("rmse_rel x_mean          = %.3e\n", err_x_mean);
fprintf("rmse_rel y_mean          = %.3e\n", err_y_mean);
fprintf("rmse_rel predictions     = %.3e\n", err_preds);

tol = 1e-12;
failed = (err_coefs > tol) || (err_x_mean > tol) || ...
         (err_y_mean > tol) || (err_preds > tol);
if failed
    fprintf(2, "PARITY GATE FAIL (tol = %.1e)\n", tol);
    exit(1);
end
fprintf("PARITY GATE PASS\n");
end

function s = read_fixture(path)
% Minimal hand-rolled JSON reader covering the fixed schema written by
% bindings/js/test/generate_parity_fixture.py. Uses jsondecode where
% available (MATLAB R2016b+, Octave 7+), falls back to a small inline
% parser otherwise. The fixture format is documented in the generator.

if exist("jsondecode") == 2 || exist("jsondecode") == 5
    fid = fopen(path, "r");
    txt = fread(fid, Inf, "uint8=>char")';
    fclose(fid);
    s = jsondecode(txt);
    return;
end

% Fallback: only fields we need, parsed by regex. Used on older Octave.
fid = fopen(path, "r");
txt = fread(fid, Inf, "uint8=>char")';
fclose(fid);

s.pls4all_version = regexp(txt, ...
    '"pls4all_version"\s*:\s*"([^"]+)"', "tokens", "once"){1};
s.n = sscanf(regexp(txt, '"n"\s*:\s*([0-9]+)', "tokens", "once"){1}, "%d");
s.p = sscanf(regexp(txt, '"p"\s*:\s*([0-9]+)', "tokens", "once"){1}, "%d");
s.q = sscanf(regexp(txt, '"q"\s*:\s*([0-9]+)', "tokens", "once"){1}, "%d");
s.n_components = sscanf(regexp(txt, ...
    '"n_components"\s*:\s*([0-9]+)', "tokens", "once"){1}, "%d");
s.coefficients = parse_array(txt, "coefficients");
s.x_mean = parse_array(txt, "x_mean");
s.y_mean = parse_array(txt, "y_mean");
s.predictions = parse_array(txt, "predictions");
end

function v = parse_array(txt, name)
pat = sprintf('"%s"\\s*:\\s*\\[([^\\]]+)\\]', name);
body = regexp(txt, pat, "tokens", "once"){1};
v = sscanf(strrep(body, ",", " "), "%f");
end
