"""nirs4all-methods — full umbrella package (M9 scaffold).

This file is a placeholder. The real __init__ is generated by
catalog/scripts/render_subset.py from catalog/subsets/nirs4all_methods.yaml.

Importing this module before M9 lands will raise ImportError to make
the staging state visible.
"""
raise ImportError(
    "nirs4all_methods is in M9 scaffold state — the actual extension "
    "(vendored sources compiled via ctypes) lands in the focused M9 "
    "session. Use the legacy 'pls4all' package or build from the "
    "unified repo source directly until then. See M9/STATUS.md."
)
