"""Read the committed chemometrics4all validation registry snapshot.

The snapshot is generated by ``python -m benchmarks.validation.export_registry
--write`` and stored under ``benchmarks/validation/registry``. This reader is
stdlib-only so Sphinx/doc payload generation can expose validation contracts
without importing the benchmark orchestrator or chemometrics runtime bindings.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_REGISTRY_DIR = ROOT / "benchmarks" / "validation" / "registry"
DEFAULT_TRUTH_SOURCES_LOCK = ROOT / "benchmarks" / "truth_sources.lock.json"

SNAPSHOT_FILES: tuple[str, ...] = (
    "manifest.json",
    "methods.json",
    "references.json",
    "datasets.json",
    "comparators.json",
    "tolerances.json",
    "suites.json",
)


@dataclass(frozen=True)
class ValidationSnapshot:
    registry_dir: Path
    manifest: dict[str, Any] = field(default_factory=dict)
    methods: list[dict[str, Any]] = field(default_factory=list)
    references: list[dict[str, Any]] = field(default_factory=list)
    datasets: list[dict[str, Any]] = field(default_factory=list)
    comparators: list[dict[str, Any]] = field(default_factory=list)
    tolerances: list[dict[str, Any]] = field(default_factory=list)
    suites: list[dict[str, Any]] = field(default_factory=list)
    truth_sources: dict[str, dict[str, Any]] = field(default_factory=dict)
    errors: tuple[str, ...] = ()

    @property
    def is_loaded(self) -> bool:
        return not self.errors and bool(self.manifest) and bool(self.methods)

    def method_contract(self, method_id: str) -> dict[str, Any] | None:
        method = self._methods_by_id().get(method_id)
        if method is None:
            return None
        tolerance = self._tolerances_by_method().get(method_id, {})
        comparator_id = method.get("comparator") or tolerance.get("comparator")
        comparator_detail = self._comparators_by_id().get(comparator_id, {})

        suite_rows = []
        dataset_ids: set[str] = set()
        for suite in self.suites:
            if method_id in suite.get("methods", []):
                ids = list(suite.get("datasets", []))
                dataset_ids.update(ids)
                suite_rows.append({
                    "id": suite.get("id"),
                    "description": suite.get("description", ""),
                    "datasets": ids,
                    "comparators": list(suite.get("comparators", [])),
                })

        datasets_by_id = self._datasets_by_id()
        datasets = sorted(
            (datasets_by_id[item] for item in dataset_ids if item in datasets_by_id),
            key=lambda row: (int(row.get("n", 0)), int(row.get("p", 0))),
        )

        truth_source_ids = list(method.get("truth_sources", []))
        truth_details = {
            source_id: dict(self.truth_sources.get(source_id, {}))
            for source_id in truth_source_ids
        }

        return {
            "method_id": method_id,
            "label": method.get("label", ""),
            "family": method.get("family", ""),
            "operation": method.get("operation", ""),
            "metrics": list(method.get("metrics", [])),
            "truth_sources": truth_source_ids,
            "truth_source_details": truth_details,
            "py_class": method.get("py_class", ""),
            "c_prefix": method.get("c_prefix", ""),
            "r_expr": method.get("r_expr", ""),
            "max_cols": method.get("max_cols"),
            "compare_internal": bool(method.get("compare_internal", False)),
            "comparator": comparator_id,
            "comparator_detail": dict(comparator_detail),
            "tolerance_quality": method.get("tolerance_quality", ""),
            "binding_tolerance": tolerance.get("binding_tolerance"),
            "reference_rtol": tolerance.get("reference_rtol"),
            "reference_atol": tolerance.get("reference_atol"),
            "default_dataset": dict(method.get("default_dataset", {})),
            "references": [dict(ref) for ref in method.get("references", [])],
            "suites": sorted(suite_rows, key=lambda row: row.get("id") or ""),
            "datasets": datasets,
        }

    def method_ids(self) -> list[str]:
        return sorted(self._methods_by_id())

    def dashboard_payload(self) -> dict[str, Any]:
        if not self.is_loaded:
            return {
                "schema_version": 0,
                "available": False,
                "errors": list(self.errors),
                "methods": {},
                "comparators": {},
                "datasets": {},
                "references": {},
                "suites": [],
            }

        methods: dict[str, dict[str, Any]] = {}
        for record in self.methods:
            method_id = record.get("method_id")
            if not method_id:
                continue
            contract = self.method_contract(str(method_id)) or {}
            methods[str(method_id)] = {
                "label": contract.get("label", ""),
                "family": contract.get("family", ""),
                "operation": contract.get("operation", ""),
                "metrics": contract.get("metrics", []),
                "truth_sources": contract.get("truth_sources", []),
                "comparator": contract.get("comparator"),
                "tolerance_quality": contract.get("tolerance_quality", ""),
                "binding_tolerance": contract.get("binding_tolerance"),
                "reference_rtol": contract.get("reference_rtol"),
                "reference_atol": contract.get("reference_atol"),
                "references": [
                    {
                        "backend": ref.get("backend"),
                        "library": ref.get("library"),
                        "language": ref.get("language"),
                        "compare": ref.get("compare"),
                        "gate_c4a": ref.get("gate_c4a"),
                    }
                    for ref in contract.get("references", [])
                ],
                "default_dataset": contract.get("default_dataset", {}),
            }

        return {
            "schema_version": int(self.manifest.get("schema_version") or 0),
            "available": True,
            "source": self.manifest.get("source"),
            "counts": dict(self.manifest.get("counts", {})),
            "methods": methods,
            "comparators": {
                row.get("id"): dict(row)
                for row in self.comparators
                if row.get("id")
            },
            "datasets": {
                row.get("id"): dict(row)
                for row in self.datasets
                if row.get("id")
            },
            "references": {
                row.get("backend"): dict(row)
                for row in self.references
                if row.get("backend")
            },
            "suites": [dict(row) for row in self.suites],
        }

    def _methods_by_id(self) -> dict[str, dict[str, Any]]:
        return {
            str(row.get("method_id")): row
            for row in self.methods
            if row.get("method_id")
        }

    def _tolerances_by_method(self) -> dict[str, dict[str, Any]]:
        return {
            str(row.get("method")): row
            for row in self.tolerances
            if row.get("method")
        }

    def _comparators_by_id(self) -> dict[str, dict[str, Any]]:
        return {
            str(row.get("id")): row
            for row in self.comparators
            if row.get("id")
        }

    def _datasets_by_id(self) -> dict[str, dict[str, Any]]:
        return {
            str(row.get("id")): row
            for row in self.datasets
            if row.get("id")
        }


def _read_json_file(path: Path) -> tuple[Any, str | None]:
    if not path.exists():
        return None, f"missing file: {path.name}"
    try:
        return json.loads(path.read_text(encoding="utf-8")), None
    except (OSError, json.JSONDecodeError) as exc:
        return None, f"{path.name}: {exc}"


def _list_or_empty(value: Any, key: str) -> list[dict[str, Any]]:
    if isinstance(value, dict) and isinstance(value.get(key), list):
        return [row for row in value[key] if isinstance(row, dict)]
    return []


def _truth_sources(path: Path = DEFAULT_TRUTH_SOURCES_LOCK) -> dict[str, dict[str, Any]]:
    data, error = _read_json_file(path)
    if error or not isinstance(data, dict):
        return {}
    sources = data.get("sources")
    if not isinstance(sources, dict):
        return {}
    return {
        str(key): dict(value)
        for key, value in sources.items()
        if isinstance(value, dict)
    }


def load_snapshot(
    registry_dir: Path | str = DEFAULT_REGISTRY_DIR,
) -> ValidationSnapshot:
    registry_dir = Path(registry_dir)
    errors: list[str] = []

    manifest_data, manifest_error = _read_json_file(registry_dir / "manifest.json")
    if manifest_error:
        errors.append(manifest_error)
    manifest = manifest_data if isinstance(manifest_data, dict) else {}

    methods_data, methods_error = _read_json_file(registry_dir / "methods.json")
    if methods_error:
        errors.append(methods_error)
    references_data, references_error = _read_json_file(registry_dir / "references.json")
    if references_error:
        errors.append(references_error)
    datasets_data, datasets_error = _read_json_file(registry_dir / "datasets.json")
    if datasets_error:
        errors.append(datasets_error)
    comparators_data, comparators_error = _read_json_file(registry_dir / "comparators.json")
    if comparators_error:
        errors.append(comparators_error)
    tolerances_data, tolerances_error = _read_json_file(registry_dir / "tolerances.json")
    if tolerances_error:
        errors.append(tolerances_error)
    suites_data, suites_error = _read_json_file(registry_dir / "suites.json")
    if suites_error:
        errors.append(suites_error)

    return ValidationSnapshot(
        registry_dir=registry_dir,
        manifest=manifest,
        methods=_list_or_empty(methods_data, "methods"),
        references=_list_or_empty(references_data, "references"),
        datasets=_list_or_empty(datasets_data, "datasets"),
        comparators=_list_or_empty(comparators_data, "comparators"),
        tolerances=_list_or_empty(tolerances_data, "tolerances"),
        suites=_list_or_empty(suites_data, "suites"),
        truth_sources=_truth_sources(),
        errors=tuple(errors),
    )


__all__ = [
    "DEFAULT_REGISTRY_DIR",
    "SNAPSHOT_FILES",
    "ValidationSnapshot",
    "load_snapshot",
]
