"""Unified parity gate for n4m.

Mirrors `pls4all/parity/python_generator/scripts/...` and the
`parity-gate.yml` CI workflow contract.

Four stages:

  Stage 0 — Generator environment: verify fixture generation is running under
            the pinned `parity/python_generator/requirements-lock.txt` stack.

  Stage 1 — Fixture determinism: regenerate every `parity/fixtures/*_v1.json`
            from the per-phase generators and verify byte-for-byte equality
            with the committed copy. Catches algorithmic drift in the
            frozen NumPy references.

  Stage 2 — Frozen-ref cross-validation: where a frozen `n4m_parity_*_ref/`
            module ships with a `validate_*.py` helper, run it against the
            actually-installed upstream package (numpy, scipy, sklearn,
            pywt, pybaselines, nirs4all). Catches drift of the frozen ref
            from the canonical reference. This is a hard gate unless
            `--reference-parity-informational` is passed. Expected skips live
            in `parity/divergences.json`.

  Stage 3 — C++ parity tests: invoke the built `n4m_tests`
            binary; every fixture under `parity/fixtures/` is loaded and
            asserted to within its declared tolerance.

Usage:
    python parity/python_generator/scripts/run_parity_gate.py \
        --build-dir build/dev-debug \
        [--skip-fixture-regen] [--skip-cpp-tests] [--skip-cross-validation]

Exit codes:
    0  — all gates pass
    1  — Stage 1 drift detected (fixture regeneration changed bytes)
    2  — Stage 3 failure (C++ parity tests broke)
    3  — Stage 1 generator crashed
    4  — Stage 0 generator environment does not match the lockfile
    5  — Stage 2 reference parity failed or timed out
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent.parent
FIXTURE_DIR = REPO_ROOT / "parity" / "fixtures"
MANIFEST_PATH = FIXTURE_DIR / "manifest.json"
GENERATOR_DIR = HERE
GENERATOR_LOCK_PATH = GENERATOR_DIR.parent / "requirements-lock.txt"

LOCKED_GENERATOR_MODULES = {
    "numpy": "numpy",
    "scipy": "scipy",
    "scikit-learn": "sklearn",
    "PyWavelets": "pywt",
    "pybaselines": "pybaselines",
}


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def snapshot_fixtures() -> dict[str, str]:
    """SHA256 of every committed fixture for drift comparison.

    `manifest.json` is excluded — it is the SHA-pinned snapshot itself.
    """
    return {
        p.name: sha256_file(p)
        for p in sorted(FIXTURE_DIR.glob("*.json"))
        if p.name != "manifest.json"
    }


def load_manifest() -> dict[str, dict[str, object]] | None:
    """Load `parity/fixtures/manifest.json` if present.

    Returns the `{fixture_name: {sha256, bytes}}` map or None when the
    manifest is missing (older checkouts before the manifest existed).
    """
    if not MANIFEST_PATH.exists():
        return None
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("fixtures") or None


def write_manifest(snapshot: dict[str, str]) -> None:
    """Write the fixture manifest for the current on-disk fixture snapshot."""
    fixtures: dict[str, dict[str, object]] = {}
    for fname, sha in sorted(snapshot.items()):
        path = FIXTURE_DIR / fname
        fixtures[fname] = {
            "sha256": sha,
            "bytes": path.stat().st_size,
        }
    payload = {
        "description": (
            "SHA-256 + byte count for every committed parity fixture. Used by "
            "parity-gate Stage 1 to detect drift between regenerated fixtures "
            "and the committed snapshot. Generated by "
            "parity/python_generator/scripts/run_parity_gate.py; do not edit by hand."
        ),
        "fixtures": fixtures,
    }
    MANIFEST_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def list_generators() -> list[Path]:
    """All per-phase generator scripts in dependency-ordered execution order."""
    return sorted(GENERATOR_DIR.glob("generate_*.py"))


def _locked_versions() -> dict[str, str]:
    """Parse top-level version pins from requirements-lock.txt."""
    pins: dict[str, str] = {}
    if not GENERATOR_LOCK_PATH.exists():
        return pins
    pattern = re.compile(r"^([A-Za-z0-9_.-]+)==([^\\s#]+)")
    for line in GENERATOR_LOCK_PATH.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line.strip())
        if match:
            pins[match.group(1)] = match.group(2)
    return pins


def stage0_generator_environment(verbose: bool = True) -> tuple[int, list[str]]:
    """Verify that fixture regeneration runs under the pinned generator env."""
    if verbose:
        print("\n=== Stage 0: generator environment ===\n")

    pins = _locked_versions()
    failures: list[str] = []

    if not pins:
        failures.append(f"lock file missing or empty: {GENERATOR_LOCK_PATH}")

    for dist_name, module_name in LOCKED_GENERATOR_MODULES.items():
        expected = pins.get(dist_name)
        if expected is None:
            failures.append(f"{dist_name}: missing from {GENERATOR_LOCK_PATH.name}")
            continue
        try:
            module = importlib.import_module(module_name)
            actual = getattr(module, "__version__", "unknown")
        except Exception as exc:  # noqa: BLE001
            failures.append(f"{dist_name}: import failed ({exc})")
            continue
        if verbose:
            print(f"  {dist_name:<14} expected {expected:<10} actual {actual}")
        if actual != expected:
            failures.append(f"{dist_name}: expected {expected}, got {actual}")

    if failures:
        if verbose:
            print("\n  [FAIL] Fixture regeneration must use the pinned lockfile env.")
        return 4, failures

    if verbose:
        print("\n  [PASS] Generator dependencies match requirements-lock.txt.")
    return 0, []


def stage1_fixture_determinism(
    verbose: bool = True,
    *,
    update_manifest: bool = False,
) -> tuple[int, list[str]]:
    """Regenerate every fixture and verify SHAs against the committed manifest.

    The manifest (`parity/fixtures/manifest.json`) is the source of truth:
    Stage 1 regenerates every fixture, hashes the result, and compares each
    SHA-256 + byte count against the manifest entry. This catches drift in
    BOTH directions — generator changes that produce different bytes, AND
    an out-of-date manifest that has not been refreshed after a deliberate
    fixture update.

    Falls back to the legacy "before/after on-disk" diff when the manifest
    is absent.
    """
    failures: list[str] = []
    crashes: list[str] = []

    manifest = load_manifest()
    before = snapshot_fixtures()
    generators = list_generators()

    if verbose:
        print(f"\n=== Stage 1: fixture determinism ({len(generators)} generators) ===\n")
        if manifest is not None:
            print(f"  Manifest present: {len(manifest)} pinned fixtures.")
        else:
            print("  Manifest missing — falling back to on-disk before/after diff.")

    for gen in generators:
        rel = gen.relative_to(REPO_ROOT)
        if verbose:
            print(f"  Running {rel.name} ...", end=" ", flush=True)
        try:
            subprocess.run(
                [sys.executable, str(gen)],
                check=True,
                capture_output=True,
                text=True,
                cwd=str(REPO_ROOT),
                timeout=120,
            )
            if verbose:
                print("ok")
        except subprocess.CalledProcessError as e:
            crashes.append(str(rel))
            if verbose:
                tail = (e.stderr or "").splitlines()[-5:]
                print(f"CRASHED\n     {chr(10).join(tail)}")
        except subprocess.TimeoutExpired:
            crashes.append(str(rel))
            if verbose:
                print("TIMEOUT")

    after = snapshot_fixtures()
    drifted: list[str] = []

    if update_manifest and not crashes:
        write_manifest(after)
        if verbose:
            print(f"\n  Updated {MANIFEST_PATH.relative_to(REPO_ROOT)} "
                  f"with {len(after)} fixtures.")
        manifest = load_manifest()

    if manifest is not None:
        # Manifest-pinned comparison: every regenerated fixture's bytes/sha
        # must match the manifest exactly.
        for fname, entry in sorted(manifest.items()):
            expected_sha = entry.get("sha256")
            expected_bytes = entry.get("bytes")
            path = FIXTURE_DIR / fname
            if not path.exists():
                drifted.append(f"{fname}: vanished after regen (manifest expected)")
                continue
            actual_sha = after.get(fname)
            actual_bytes = path.stat().st_size
            if actual_sha != expected_sha:
                drifted.append(
                    f"{fname}: SHA changed ({str(expected_sha)[:8]} -> "
                    f"{str(actual_sha)[:8]})"
                )
            elif actual_bytes != expected_bytes:
                drifted.append(
                    f"{fname}: byte count changed ({expected_bytes} -> {actual_bytes})"
                )
        new_files = set(after) - set(manifest)
        for f in sorted(new_files):
            drifted.append(f"{f}: new file created without manifest entry")
    else:
        # Legacy fallback: pure on-disk before/after.
        for fname, sha_before in before.items():
            sha_after = after.get(fname)
            if sha_after is None:
                drifted.append(f"{fname}: vanished after regen")
            elif sha_before != sha_after:
                drifted.append(f"{fname}: SHA changed ({sha_before[:8]} -> {sha_after[:8]})")
        for f in sorted(set(after) - set(before)):
            drifted.append(f"{f}: new file created (uncommitted)")

    if verbose:
        if crashes:
            print(f"\n  Generators crashed: {len(crashes)}")
            for c in crashes:
                print(f"    - {c}")
        if drifted:
            print(f"\n  Fixtures drifted: {len(drifted)}")
            for d in drifted[:20]:
                print(f"    - {d}")
        if not crashes and not drifted:
            ref = "manifest" if manifest is not None else "on-disk snapshot"
            print(f"\n  [PASS] All {len(after)} fixtures bit-identical to {ref}.")

    exit_code = 0
    if crashes:
        exit_code = 3
        failures.extend([f"generator crash: {c}" for c in crashes])
    if drifted:
        exit_code = 1 if exit_code == 0 else exit_code
        failures.extend([f"fixture drift: {d}" for d in drifted])

    return exit_code, failures


def stage2_cross_validation(
    *,
    informational: bool = False,
    verbose: bool = True,
) -> tuple[int, list[str]]:
    """Run the Gate-2 reference-parity runner (``run_reference_parity.py``).

    Tests every operator against the *canonical* upstream implementation
    (numpy / scipy / sklearn / pywt / pybaselines / nirs4all). The runner
    enforces ``parity/divergences.json``: FAIL results always fail this
    stage, and SKIP results fail unless they are explicitly allowlisted.
    """
    if verbose:
        mode = "informational" if informational else "gating"
        print(f"\n=== Stage 2: reference parity vs upstream ({mode}) ===\n")

    runner = REPO_ROOT / "parity" / "run_reference_parity.py"
    if not runner.exists():
        if verbose:
            print(f"  Runner not found: {runner}")
        return 0, [f"runner missing: {runner}"]

    issues: list[str] = []
    try:
        result = subprocess.run(
            [
                sys.executable,
                str(runner),
                "--quiet-cases",
                "--skip-policy",
                "allowlist",
                "--divergences",
                str(REPO_ROOT / "parity" / "divergences.json"),
            ],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
            timeout=600,
        )
    except subprocess.TimeoutExpired:
        return (0 if informational else 5), [f"{runner.name}: timeout after 600s"]
    except Exception as e:  # noqa: BLE001
        return (0 if informational else 5), [f"{runner.name}: {e}"]

    if verbose:
        # Print tail of output for visibility.
        for line in result.stdout.splitlines()[-20:]:
            print(f"  {line}")
        if result.returncode != 0:
            print(f"\n  Reference parity reported failures (rc={result.returncode}).")
            issues.append(f"reference parity rc={result.returncode}")
        else:
            print(f"\n  [PASS] Reference parity passed with allowlisted skips only.")

    if informational:
        return 0, issues
    return result.returncode, issues


def stage3_cpp_tests(build_dir: Path, verbose: bool = True) -> tuple[int, list[str]]:
    """Run the C++ test binary."""
    if verbose:
        print(f"\n=== Stage 3: C++ parity tests ({build_dir}) ===\n")

    test_bin = build_dir / "cpp" / "tests" / "n4m_tests"
    if not test_bin.exists():
        return 2, [f"test binary missing: {test_bin}"]

    try:
        result = subprocess.run(
            [str(test_bin)],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
            timeout=300,
        )
    except subprocess.TimeoutExpired:
        return 2, [f"{test_bin} timed out after 300 s"]

    last_lines = result.stdout.splitlines()[-3:]
    for line in last_lines:
        if verbose:
            print(f"  {line}")

    if result.returncode != 0:
        return 2, [f"n4m_tests exited {result.returncode}"]
    return 0, []


def main() -> int:
    parser = argparse.ArgumentParser(description="nirs4all-methods parity gate runner.")
    parser.add_argument("--build-dir", default="build/dev-debug",
                        help="CMake build directory (default: build/dev-debug)")
    parser.add_argument("--skip-generator-env-check", action="store_true",
                        help="Skip Stage 0 pinned generator environment check")
    parser.add_argument("--skip-fixture-regen", action="store_true",
                        help="Skip Stage 1 (fixture determinism)")
    parser.add_argument("--update-manifest", action="store_true",
                        help="After fixture regeneration, refresh parity/fixtures/manifest.json")
    parser.add_argument("--skip-cross-validation", action="store_true",
                        help="Skip Stage 2 (frozen-ref cross-validation)")
    parser.add_argument("--skip-cpp-tests", action="store_true",
                        help="Skip Stage 3 (C++ parity tests)")
    parser.add_argument("--reference-parity-informational", action="store_true",
                        help="Run Stage 2 but do not let it influence exit status")
    args = parser.parse_args()

    exit_code = 0
    all_failures: list[str] = []

    if not args.skip_fixture_regen:
        if not args.skip_generator_env_check:
            rc, fails = stage0_generator_environment()
            exit_code = exit_code or rc
            all_failures.extend(fails)
            if rc:
                print("\n=== Parity gate summary ===")
                print(f"  [FAIL] exit_code={exit_code}")
                for f in all_failures:
                    print(f"    - {f}")
                print()
                return exit_code
        rc, fails = stage1_fixture_determinism(update_manifest=args.update_manifest)
        exit_code = exit_code or rc
        all_failures.extend(fails)

    if not args.skip_cross_validation:
        rc, fails = stage2_cross_validation(
            informational=args.reference_parity_informational
        )
        exit_code = exit_code or rc
        prefix = "[INFO] " if args.reference_parity_informational else ""
        all_failures.extend(f"{prefix}{i}" for i in fails)

    if not args.skip_cpp_tests:
        rc, fails = stage3_cpp_tests(REPO_ROOT / args.build_dir)
        exit_code = exit_code or rc
        all_failures.extend(fails)

    print("\n=== Parity gate summary ===")
    if exit_code == 0:
        print("  [PASS]")
    else:
        print(f"  [FAIL] exit_code={exit_code}")
        for f in all_failures:
            if not f.startswith("[INFO]"):
                print(f"    - {f}")
    print()

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
